import type { PortfolioProject } from "@/types";
import { IMAGES } from "@/constants/images";

export const PORTFOLIO_PROJECTS: PortfolioProject[] = [
  {
    id: "1",
    title: "Скандинавский минимализм",
    category: "two-room",
    area: 68,
    duration: "3 месяца",
    style: "Скандинавский",
    image: IMAGES.portfolio["01"].image,
    beforeImage: IMAGES.portfolio["01"].before,
    afterImage: IMAGES.portfolio["01"].after,
  },
  {
    id: "2",
    title: "Студия в ЖК «Символ»",
    category: "studio",
    area: 32,
    duration: "6 недель",
    style: "Современный",
    image: IMAGES.portfolio["02"].image,
    beforeImage: IMAGES.portfolio["02"].before,
    afterImage: IMAGES.portfolio["02"].after,
  },
  {
    id: "3",
    title: "Семейная двушка на Юго-Западе",
    category: "two-room",
    area: 58,
    duration: "2.5 месяца",
    style: "Неоклассика",
    image: IMAGES.portfolio["03"].image,
  },
  {
    id: "4",
    title: "Однушка для молодой пары",
    category: "one-room",
    area: 42,
    duration: "7 недель",
    style: "Лофт",
    image: IMAGES.portfolio["04"].image,
    beforeImage: IMAGES.portfolio["04"].before,
    afterImage: IMAGES.portfolio["04"].after,
  },
  {
    id: "5",
    title: "Студия 28 м² — smart-планировка",
    category: "studio",
    area: 28,
    duration: "5 недель",
    style: "Минимализм",
    image: IMAGES.portfolio["05"].image,
  },
  {
    id: "6",
    title: "Трёхкомнатная в Хорошёво",
    category: "two-room",
    area: 74,
    duration: "4 месяца",
    style: "Contemporary",
    image: IMAGES.portfolio["06"].image,
  },
  {
    id: "7",
    title: "Однушка в новостройке",
    category: "one-room",
    area: 38,
    duration: "6 недель",
    style: "Современный",
    image: IMAGES.portfolio["07"].image,
    beforeImage: IMAGES.portfolio["07"].before,
    afterImage: IMAGES.portfolio["07"].after,
  },
  {
    id: "8",
    title: "Студия с зонированием",
    category: "studio",
    area: 35,
    duration: "6 недель",
    style: "Japandi",
    image: IMAGES.portfolio["08"].image,
  },
  {
    id: "9",
    title: "Двушка в сталинке",
    category: "two-room",
    area: 62,
    duration: "3.5 месяца",
    style: "Классический",
    image: IMAGES.portfolio["09"].image,
  },
];

export const PORTFOLIO_FILTERS = [
  { id: "all" as const, label: "Все проекты" },
  { id: "studio" as const, label: "Студия" },
  { id: "one-room" as const, label: "Однушка" },
  { id: "two-room" as const, label: "Двушка" },
];
